### ISSUE TITLE
Compatibilty of Magic Set Technique

### ISSUE THREAD

**Issue by tanaka-de-silva** [socialite-lang/socialite#8]
Has there been any work done to consider the possibility of adding a variant of magic sets transformation for the Socialite Datalog dialect? if it is possible to do so in the first place.

**Comment by seojiwon** [comment]
Thank you for your interest.
So far, we haven't attempted to apply the magic set transformation (or
variant of it) to SociaLite.
But it should not be too hard to apply it to SociaLite, as the
transformation is essentially rule rewriting, which can be implemented as a
preprocessing.
Yet, we don't have any specific plan to apply the transformation in
SociaLite.

-Jiwon

**Comment by tanaka-de-silva** [comment]
Thank you very much for the reply. After a little bit of further research, it appears that adding magic sets based rewriting is a significant undertaking and is probably something that is out of my reach given my current understanding of Datalog. For example, I am not sure how stratification should be implemented, would one follow an approach similar to the one described in the DeALS and LDL++ papers? or does it require something else entirely. Given that this project seems to be targeted as a solution for high performance graph processing rather than as a general purpose Datalog query engine I am not sure whether the implicit ordering introduced on predicate evaluation when using a sideways information passing strategy is at all desirable (or whether it is compatible with pipelining). 

The amount of effort you (and presumably your advisor and other collaborators) have invested on this project is truly impressive and I am thankful that the resultant artefacts are freely available. From what I have seen so far there have been at least two papers, tens of thousands of LOC, a couple of recorded presentations and a pretty comprehensive thesis (I have only read a fraction of it so far). On the flip-side the sophistication of the current Java implementation, complete with code generation and Python Interop means that it is not the easiest project for a novice to get a grasp of and probably best tackled once capable of implementing the core ideas in a fresh toy project.

**Comment by seojiwon** [comment]
Thank you for your interest and comments!

I agree that it might be non-trivial to implement the magic set
transformation for SociaLite for someone new to the project, although it
shouldn't be too hard for someone who's already familiar with SociaLite.
We are currently working on refactoring and lowering the complexity to make
it easy for people to participate. Also we are working on making SociaLite
more general-purpose, so please keep an eye on the project!

Thanks,

-Jiwon
